language: scala
scala:
- 2.11.12
- 2.12.8
jdk:
- openjdk8
sudo: false
script:
- sbt clean coverage test
after_success:
- sbt coveralls
env:
  global:
    secure: HyBibyAO/aGynP136vU9Gg+WY++9F/nwGfKVBwJC6Uom5FpB/K/EPL1ZAC+LnwTqZq1rQVTKtq6VYxe1mllHks7dT5+6LX2rpAjpIwTt5KLVcHOkphkJ8cCS2ytvrZPSjmAfoJW7c/N5Jkw4ILFZiSqJDuJWIYfVhc8aUgXrCGo=
